### ISSUE TITLE
Error on spring framework

### ISSUE THREAD

**Issue by Ivan-Veselov** [ml-in-programming/RefactoringDataSet#11]
Error occurred during processing of commit https://github.com/spring-projects/spring-framework/commit/4c42597cbcd7b2f0a225a368554198f54224b1c3

```
ERROR [org.jetbrains.research.groups.ml_methods.refactoring.detection.tools.DefaultBranchesDetectionTool.detect] - Error occurred during refactoring detection for repository: https://github.com/spring-projects/spring-framework.git
java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -9
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:102)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:280)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.tools.RMiner.detect(RMiner.java:181)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.tools.RMiner.detect(RMiner.java:35)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.tools.DefaultBranchesDetectionTool.detect(DefaultBranchesDetectionTool.java:46)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.RefactoringDetectionApplication.run(RefactoringDetectionApplication.java:71)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.RefactoringDetectionApplication.main(RefactoringDetectionApplication.java:31)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -9
	at java.lang.String.substring(String.java:1967)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.replaceVariablesWithArguments(UMLOperationBodyMapper.java:1469)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1000)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:824)
	at gr.uom.java.xmi.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:218)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.checkForExtractedOperations(UMLClassBaseDiff.java:961)
	at gr.uom.java.xmi.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:89)
	at gr.uom.java.xmi.UMLClass.diff(UMLClass.java:238)
	at gr.uom.java.xmi.UMLModel.diff(UMLModel.java:143)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:138)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:97)
	... 6 more
```

**Comment by Ivan-Veselov** [comment]
This is a bug of RMiner. Made an issue in its repo.
