### ISSUE TITLE
Error on glide project

### ISSUE THREAD

**Issue by Ivan-Veselov** [ml-in-programming/RefactoringDataSet#13]
Error happened during processing of commit https://github.com/bumptech/glide/commit/86ea385b773a81e0f5c6b1bb677a752855e504e0

```
ERROR [org.jetbrains.research.groups.ml_methods.refactoring.detection.tools.DefaultBranchesDetectionTool.detect] - Error occurred during refactoring detection for repository: https://github.com/bumptech/glide.git
java.lang.RuntimeException: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
third_party/disklrucache
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:102)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:280)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.tools.RMiner.detect(RMiner.java:181)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.tools.RMiner.detect(RMiner.java:35)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.tools.DefaultBranchesDetectionTool.detect(DefaultBranchesDetectionTool.java:46)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.RefactoringDetectionApplication.run(RefactoringDetectionApplication.java:71)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.RefactoringDetectionApplication.main(RefactoringDetectionApplication.java:31)
Caused by: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
third_party/disklrucache
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:276)
	at org.refactoringminer.util.GitServiceImpl.checkout(GitServiceImpl.java:120)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:134)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:97)
	... 6 more
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
third_party/disklrucache
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:467)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:449)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:272)
	... 9 more
```

**Comment by Ivan-Veselov** [comment]
The problem is in git submodules.
`Git.cloneRepository().setDirectory(new File("/tmp/glide")).setURI("https://github.com/bumptech/glide.git").setCloneAllBranches(true).call();`
Such code with Eclipse git API clones repository with deleted submodules. This is exactly what happens inside RMiner. After that the problem arises only on mentioned commit.

**Comment by Ivan-Veselov** [comment]
Adding `setCloneSubmodules(true)` to command builder solves the problem.

**Comment by Ivan-Veselov** [comment]
But after that new problems arise.

**Comment by Ivan-Veselov** [comment]
```
error: The following untracked working tree files would be overwritten by checkout:
	third_party/disklrucache/LICENSE
	third_party/disklrucache/README.third_party
Please move or remove them before you switch branches.
Aborting
```

**Comment by Ivan-Veselov** [comment]
Problem is due to the fact that `third_party/disklrucache/LICENSE` and `third_party/disklrucache/README.third_party` were in repository until https://github.com/bumptech/glide/commit/86ea385b773a81e0f5c6b1bb677a752855e504e0. This raises conflicts during checkout on parent of that commit.
