### ISSUE TITLE
Error on testcontainers-java

### ISSUE THREAD

**Issue by Ivan-Veselov** [ml-in-programming/RefactoringDataSet#9]
https://github.com/testcontainers/testcontainers-java

```
ERROR [org.jetbrains.research.groups.ml_methods.refactoring.detection.DefaultBranchesDetectionTool.detect] - Error occurred during refactoring detection for repository: https://github.com/testcontainers/testcontainers-java.git
java.lang.RuntimeException: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
gradle/wrapper/gradle-wrapper.jar
	at org.refactoringminer.api.RefactoringHandler.handleException(RefactoringHandler.java:50)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:102)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectAll(GitHistoryRefactoringMinerImpl.java:280)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.RMiner.detect(RMiner.java:52)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.DefaultBranchesDetectionTool.detect(DefaultBranchesDetectionTool.java:43)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.RefactoringDetectionApplication.run(RefactoringDetectionApplication.java:63)
	at org.jetbrains.research.groups.ml_methods.refactoring.detection.RefactoringDetectionApplication.main(RefactoringDetectionApplication.java:23)
Caused by: org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with files: 
gradle/wrapper/gradle-wrapper.jar
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:276)
	at org.refactoringminer.util.GitServiceImpl.checkout(GitServiceImpl.java:120)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detectRefactorings(GitHistoryRefactoringMinerImpl.java:130)
	at org.refactoringminer.rm1.GitHistoryRefactoringMinerImpl.detect(GitHistoryRefactoringMinerImpl.java:97)
	... 5 more
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
gradle/wrapper/gradle-wrapper.jar
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:467)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:449)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:272)
	... 8 more
```

**Comment by Ivan-Veselov** [comment]
Problem 1: `RefactoringHandler` in `RMiner.java` should override `handleException` to log exception occurred during commit processing and skip this commit. Currently in case of a commit failure the whole session is stopped.

**Comment by Ivan-Veselov** [comment]
Problem 2: `cloneIfNotExists` uses old repository from a previous run. For us it's better to clone repository from scratch, us we don't plan to process one repository very often.
In my case old repository had a checkout conflict from a previous run and it was impossible to reproduce error without manually deleting this project from `/tmp` directory.

**Comment by Ivan-Veselov** [comment]
The actual error happens during checkout on https://github.com/testcontainers/testcontainers-java/commit/fe62ccff8724ec58ec71b4cef8b520f56ed78833

`gradle/wrapper/gradle-wrapper.jar` becomes modified and does not allow to checkout on another commit.

**Comment by Ivan-Veselov** [comment]
Probably it's somehow connected with `.gitattributes` file. May be git tries to replace EOLs in .jar file.
